//GET
export const GET_ADDRESS_REQUEST = "GET_ADDRESS_REQUEST";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_FAILURE = "GET_ADDRESS_FAILURE";

// POST
export const POST_ADDRESS_REQUEST = "POST_ADDRESS_REQUEST";
export const POST_ADDRESS_SUCCESS = "POST_ADDRESS_SUCCESS";
export const POST_ADDRESS_FAILURE = "POST_ADDRESS_FAILURE";

//UPDATE
export const PATCH_ADDRESS_REQUEST = "PATCH_ADDRESS_REQUEST";
export const PATCH_ADDRESS_SUCCESS = "PATCH_ADDRESS_SUCCESS";
export const PATCH_ADDRESS_FAILURE = "PATCH_ADDRESS_FAILURE";
